### ISSUE TITLE
labyrinth+SpongeForge Server Crash

### ISSUE THREAD

**Issue by knoxhack** [abecderic/labyrinth#1]
https://gist.github.com/knoxhack/90370893525af2bc53eed8ef0e80dd4b

**Comment by knoxhack** [comment]
https://github.com/SpongePowered/SpongeForge/issues/890

**Comment by abecderic** [comment]
Without SpongeForge this bug does not exist.

The line containing the NPE is this

```
LabyrinthChunk chunk = Labyrinth.instance.worldData.getDataForChunk(x, z, world.rand);
```

In this line `worldData` is null. `worldData` is first set in the `FMLServerStartingEvent` (the code is [here](https://github.com/abecderic/labyrinth/blob/f475ecfc2abeea981c6dda4b50d805e81adbbb98/src/main/java/com/abecderic/labyrinth/Labyrinth.java#L70)) which is not called before the crash, however `FMLServerStartingEvent` is called before worldgen when not using SpongeForge.

The event in the server lifecycle that is called earlier (`FMLServerAboutToStartEvent`) does not have the overworld loaded and so one can not get the world data from that event.

**Comment by abecderic** [comment]
Fixed in dev.
