### ISSUE TITLE
Double problems

### ISSUE THREAD

**Issue by Kashdeya** [abecderic/labyrinth#11]
I have noticed that when making a DOUBLE structure that I can not use the up function. Let me explain. I have a structure that spans 4 chunks or a DOUBLE and it goes up +6. but when i use this in the json file. 

{
    "weight":1,
    "up":6,
    "size":
    [
        "DOUBLE"
    ]
}

I get bedrock walls in the +6 section. 
like below. I have removed a little bit to show you what happens. 

![2017-05-28_12 30 19](https://cloud.githubusercontent.com/assets/3231637/26530793/6cc69294-43a1-11e7-8be6-76878fcfb4a2.png)

I have noticed even if i use +1 it adds in the bedrock on DOUBLE and TRIPLES. cause I have 2 other structures that are DOUBLE and TRIPLE and they work fine because they do not go above the default. 

Is this a bug or am I missing something here?

I am using 
MC 1.10.2
Forge 12.18.3.2297
Labyrinth 1.4

I was also wondering if you have more documentation on the  replacement section of the json other then what is in the defaults on here.

**Comment by abecderic** [comment]
I have improved world generation in the Labyrinth. The bug with Bedrock walls spawning when a room extends further up or down than default should be gone with the new version [Labyrinth-1.5](https://minecraft.curseforge.com/projects/daedalus-labyrinth/files/2430244).

I have also added new sections to the Adding rooms.md document detailing the usage of the transformations and replacements sections of the room json files.
