### ISSUE TITLE
Silly Room Size Question

### ISSUE THREAD

**Issue by Winddbourne** [abecderic/labyrinth#15]
Looking at the example and equation it seems like room size should be:

[Simplified]
size_in_blocks = size_in_chunks * 16 - 1
                          size-in-chunks * (16-1)
                          size_in_chunks*15

Which adds up with the example where a one chunk room as a 15X15 square. 

I want to make sure of this as the accepted room sizes aren't even squares extending outward.  Do I have this right:

X2 = 30X15     Z2 = 15X30
X3 = 45X15     Z3 = 15X45
X4 = 60X15     Z4 = 60X15

Triple = 45X45

Am I understanding this correctly?

**Comment by abecderic** [comment]
No, you put the parenthesis wrong. Correct is: `size_in_blocks = (size_in_chunks * 16) - 1`.

A one chunk room, a SINGLE, is 15x15 blocks. When you combine two neighboring rooms into one, you get the size of both rooms plus the wall that would have been in the middle, so the size of X2 is 31x15 blocks.

The largest room, a TRIPLE, would then be 47x47 blocks.

**Comment by Winddbourne** [comment]
Sometimes it is good to ask silly questions,   :)
