### ISSUE TITLE
(Suggestion) make a config to make the daedilium structure to spawn alone.

### ISSUE THREAD

**Issue by stefanovich123** [abecderic/labyrinth#16]
I want to create a modpack and I dislike the vanilla villages so I disabled them but then the structure doesn't spawn.
Can you make a config to make the structure to spawn standalone.
(And I use Noworldgen5you to disable the villages)

**Comment by abecderic** [comment]
Daedalus' Workshop is a village building, I can't easily make it spawn standalone.

However if you're going to create your own structures like you mentioned in an earlier version of your issue, you can spawn the Daedalus' Blocks in the correct configuration yourself: Place two Daedalus' Blocks on top of each other and then right-click the top block with a stick while in Creative Mode to turn it into a Daedalus Block with the delta. The you have the correct configuration for the portal to form. (Like seen in the workshops in the villages.)

**Comment by stefanovich123** [comment]
Oh I should use a stick.
Thank you very much.
I will close this issue beccause you already provided my answer.
