### ISSUE TITLE
Servercrash during worldgen while exploring

### ISSUE THREAD

**Issue by Saereth** [abecderic/labyrinth#2]
we're working on adding mods to our 1.10.2 modpack, when we added your mod however we're seeing a crash now during worldgen.

here is a copy of the crash report https://gist.github.com/Saereth/f4bd1bd973db185ca0f57ab7da5fc844

This seems to occur while exploring and then once we restart the server its fine until randomly it will happen later as people continue to explore the dimension. 

version 1.1 of your mod, forge version 2077

**Comment by abecderic** [comment]
Fixed in version 1.2
