### ISSUE TITLE
No information regarding use of your mod in modpacks

### ISSUE THREAD

**Issue by DrPlantabyte** [abecderic/labyrinth#3]
You claim "All rights reserved" on the Curseforge page and do not post any exceptions, meaning that everyone who uses your mod is technically violating your copyright. Please could you add a license or modpack policy statement to clarify whether or not you allow other people to use your mod (and whether you allow your mod to be redistributed in public modpacks)?

**Comment by abecderic** [comment]
I have added the following policy statement to the curseforge page which should answer your questions.

```
You can use Daedalus' Labyrinth in your modpack,
but monetization (apart from Curse rewards program) is not allowed.
```
