### ISSUE TITLE
Question about room creation - other mods blocks 

### ISSUE THREAD

**Issue by maxiride** [abecderic/labyrinth#8]
I'd like to ask if following the guide in the wiki is possible to add rooms with other mods items in it.

How does labyrinth handle it with "foreign" blocks/fluids? 

Also the weight, is there any reference about the spawn probability? 
For instance the weight 1 which if I understood correctly is the rarest ratio, does it mean 1 room every N chunks with N being what?

**Comment by abecderic** [comment]
Yes, it is possible to add rooms with other mods blocks and fluids. Daedalus' Labyrinth will use those blocks just fine. If a block from another mod was used in a room and that mod is missing, then the Labyrinth will just spawn nothing there (the block will be air).

The weight is against the total weight of all rooms, i.e. if you have 4 rooms: A with weight 1, B with weight 1, C with weight 2 and D with weight 3, then the total weight is 7 (your N) and the probabilities are: A: 1/7, B: 1/7, C: 2/7, D: 3/7

**Comment by maxiride** [comment]
Awesome. It opens endless possibilities! Great job  with this mod  ;)
